/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package TheBusiness.ProductManagement;

import ProductPerformance.ProductPerformance;
import TheBusiness.Business.Business;
import TheBusiness.Supplier.Supplier;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hanlinyao
 */
public class SimulationResultJPanel extends javax.swing.JPanel {
    private JPanel CardSequencePanel;
    private Business business;

    /**
     * Creates new form SimulationResultJPanel
     */
    public SimulationResultJPanel(Business bz, JPanel jp) {
        this.business = bz;
        this.CardSequencePanel = jp;
        initComponents();
        this.setBackground(new java.awt.Color(0, 153, 153)); // 设置背景颜色
        populateSimulationTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        MaxMargins = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        FinalReports = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Product Name", "Old Target Price", "New Target Price", "Simulated Sales Volume", "Simulated Margin"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        MaxMargins.setText("Maximize Product Margins");
        MaxMargins.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MaxMarginsActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Simulation Reports ");

        FinalReports.setText("See Final Reports");
        FinalReports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FinalReportsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 743, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(258, 258, 258)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(MaxMargins)
                        .addGap(56, 56, 56)
                        .addComponent(FinalReports)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addGap(4, 4, 4)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MaxMargins)
                    .addComponent(FinalReports))
                .addGap(52, 52, 52))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        CardSequencePanel.remove(this);
        ((CardLayout) CardSequencePanel.getLayout()).previous(CardSequencePanel);
    
    }//GEN-LAST:event_jButton1ActionPerformed

    private void MaxMarginsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MaxMarginsActionPerformed
        //Parker making this maximize profit method.
        
        int selectedRow = jTable1.getSelectedRow();
          if (selectedRow >= 0) {
            ProductSummary selectedsummary = (ProductSummary) jTable1.getValueAt(selectedRow, 0);
            Product selectedproduct = selectedsummary.getSubjectproduct();
            //add new change in case not already captured.
            ArrayList<ChangeRecord> records = new ArrayList();
            selectedproduct.setRecords(records);
            selectedproduct.newchange(selectedproduct.getTargetPrice());
           //selectedsummary.maxTargetPrice(selectedsummary);

            //create local variables for pricing, kinda REDUNDANT
            int tprice = selectedproduct.getTargetPrice();
            int Lprice = selectedproduct.getFloorPrice();
            int Hprice = selectedproduct.getCeilingPrice();
           
         
//   
           while (true) {
                       //move prices up and down depending on the target price marigns approach zero as product prices are optimized to allign target price with what people are actually willing to pay.
             int performance = selectedsummary.getProductPricePerformance();

             if (performance > 0) {
               selectedproduct.adjustTargetPrice(+1);
           } else if (performance < 0) {
               selectedproduct.adjustTargetPrice(-1);
           } else {
               break; // neutral
                 }

    // stop if bounds are hit
    if (selectedproduct.getTargetPrice() == selectedproduct.getCeilingPrice() ||
        selectedproduct.getTargetPrice() == selectedproduct.getFloorPrice()) {
        break;
    }
}

             JOptionPane.showMessageDialog(CardSequencePanel, "Profit Maximized!");
            
            populateSimulationTable();
            
           
            
          }
            
        
        
    }//GEN-LAST:event_MaxMarginsActionPerformed

    private void FinalReportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FinalReportsActionPerformed
       ProductPerformance Panel = new ProductPerformance(business, CardSequencePanel);
       CardSequencePanel.add("Final Reports Panel", Panel);

        CardLayout layout = (CardLayout) CardSequencePanel.getLayout();
       
        layout.next(CardSequencePanel);
     
       
    }//GEN-LAST:event_FinalReportsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton FinalReports;
    private javax.swing.JButton MaxMargins;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

    private void populateSimulationTable() {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0); // 清空表格内容
        // 遍历所有供应商及其产品
        ArrayList<Supplier> supplierList = business.getSupplierDirectory().getSuplierList();

        for (Supplier s : supplierList) {
            ProductCatalog pc = s.getProductCatalog();
            for (Product pt : pc.getProductList()) {
                
                // 1. 生成产品摘要（ProductSummary）以获取模拟绩效
                // 注意：ProductSummary 会使用产品当前设置的 targetPrice 来计算性能。
                ProductSummary simulatedSummary = new ProductSummary(pt);
                
                // 2. 准备行数据
                Object[] row = new Object[5];
                row[0] = simulatedSummary; // Product-Parker
                
                // *** 重要说明：获取“旧目标价格”需要更复杂的逻辑来保存历史数据。
                // *** 鉴于当前项目结构，我们暂时使用当前目标价作为占位符，但在实际项目中，
                // *** 您需要在调整价格前将旧价格保存在一个单独的变量或数据结构中。
                int oldTargetPrice = pt.getTargetPrice(); // 仅为占位符
                
                row[1] = oldTargetPrice; // Old Target Price (应是调整前的价格)
                row[2] = pt.getTargetPrice(); // New Target Price (当前价格)
                row[3] = simulatedSummary.getSalesRevenues(); // Simulated Sales Volume (使用实际销售额)
                row[4] = simulatedSummary.getProductPricePerformance(); // Simulated Margin (使用当前目标价计算的利润性能)
                
                model.addRow(row);
            }
        }
    }
        
}
